name: build targets
on: [pull_request]
jobs:
  build:
    if: github.repository == 'QW-Group/ezquake-source'
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
       target: [windows-glsl-x64, windows-std-x64, windows-multi-x64]
       include:
         - target: windows-glsl-x64
           config: rls-modern
           platform: x64
         - target: windows-std-x64
           config: rls-classic
           platform: x64
         - target: windows-multi-x64
           config: rls-all
           platform: x64

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Build txt2c
      run: msbuild misc\vstudio\txt2c\txt2c.vcxproj -t:rebuild -property:Configuration=Release

    - name: Make dir
      run: mkdir .vs

    - name: Copy txt2c
      run: cp misc\vstudio\txt2c\.vs\txt2c.exe .vs\

    - name: Build ezquake
      run: msbuild ezQuake.vcxproj -t:rebuild -property:Configuration=${{ matrix.config }} -property:Platform=${{ matrix.platform }}

    - name: Archive client
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.target }}
        path: .vs\${{ matrix.platform }}\${{ matrix.config }}\Output\ezQuake.exe
